In [1]:
import numpy as np

In [4]:
print(type([1,2,3]))
print(type((1,2,3)))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [3]:
np.zeros(5)#1 solo numero para un areglo
np.zeros([5,5])
np.zeros((5,5)
np.zeros([1000,200])
np.zeros((2,3,4,5))

SyntaxError: invalid syntax (<ipython-input-3-994782c3344e>, line 4)

In [5]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [7]:
np.arange(-12,1)

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [8]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
len(np.zeros(20).reshape(2,5,2).reshape(20))

20

In [20]:
np.ones(12).reshape(4,3).shape

(4, 3)

In [23]:
a=np.array([10,10,10])
b=np.array([5,5,5])
a+b

array([15, 15, 15])

In [24]:

a-b

array([5, 5, 5])

In [25]:
a-8

array([2, 2, 2])

In [26]:
a*3 #multiplicacion

array([30, 30, 30])

In [27]:
a/b #divicion

array([2., 2., 2.])

In [28]:
a % b

array([0, 0, 0])

In [30]:
muestra = np.arange(20).reshape(5,2,2)

In [32]:
muestra > 5


array([[[False, False],
        [False, False]],

       [[False, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [33]:
muestra[muestra > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [52]:
muestra = np.arange(20).reshape(5,2,2)
respuesta_glucosa = (muestra % 2==0)&(muestra>5)&(muestra<14)
muestra[respuesta_glucosa]

array([ 6,  8, 10, 12])

In [51]:
respuesta_glucosa = (muestra > 5) & (muestra < 14) & (muestra % 2 == 0)
muestra[respuesta_glucosa]

array([ 6,  8, 10, 12])

In [49]:
respuesta_glucosa = (((muestra > 5) <14) % 2 == 0)


In [2]:
#producto punto
A=np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [3]:
B=np.arange(4,8).reshape((2,2))
B

array([[4, 5],
       [6, 7]])

In [4]:
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [5]:
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [8]:
arreglo_doce=np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
arreglo_doce.sum()

66

In [10]:
arreglo_doce.min()

0

In [11]:
arreglo_doce.max()

11

In [12]:
arreglo_doce.reshape(3,2,2).sum()

66

In [13]:
arreglo_doce.reshape(3,2,2).sum(axis=0)

array([[12, 15],
       [18, 21]])

In [14]:
arreglo_doce.reshape(3,2,2).sum(axis=1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])