In [1]:
import numpy as np

In [2]:
arreglo_grados=np.array([0,30,45,60,90])
arreglo_grados

array([ 0, 30, 45, 60, 90])

In [3]:
arreglo_radianes = arreglo_grados * np.pi/100
arreglo_radianes

array([0.        , 0.9424778 , 1.41371669, 1.88495559, 2.82743339])

In [4]:
np.sin(arreglo_radianes)

array([0.        , 0.80901699, 0.98768834, 0.95105652, 0.30901699])

In [6]:
arreglo_randomico=np.random.randint(11)
arreglo_randomico

5

In [9]:
numero_random_negativo=np.random.randint(-9,2)
numero_random_negativo

1

In [13]:
arreglo_random=np.random.randint(10,20,8)
arreglo_random

array([11, 17, 14, 17, 13, 13, 17, 11])

In [16]:
np.random.rand(9,3,3)

array([[[1.60726252e-01, 3.70786568e-01, 9.17408068e-01],
        [7.42486762e-01, 3.86620491e-01, 7.11005343e-02],
        [4.44577608e-01, 6.23025978e-01, 1.44002874e-01]],

       [[4.16310989e-01, 5.06426540e-01, 6.58273676e-02],
        [9.37612107e-01, 3.18552021e-01, 8.85378118e-01],
        [9.24168013e-04, 2.14861049e-01, 1.41243912e-03]],

       [[6.00419427e-01, 6.77716801e-01, 5.93963965e-01],
        [5.87466805e-02, 8.42554854e-01, 2.29724804e-01],
        [6.62211161e-01, 3.55104168e-01, 7.00294925e-01]],

       [[2.68743997e-01, 2.69226770e-01, 9.67108443e-01],
        [9.01497001e-01, 3.21367851e-01, 2.77108797e-01],
        [6.30568355e-01, 9.53329382e-01, 2.38208786e-01]],

       [[5.14470732e-01, 7.44509828e-01, 6.82042880e-01],
        [4.03732158e-01, 9.79529535e-01, 2.18947414e-01],
        [7.00776282e-01, 3.85499036e-01, 8.64842422e-01]],

       [[6.23778718e-01, 1.12919393e-01, 8.52752950e-01],
        [1.62378546e-01, 2.12515498e-01, 4.36816501e-01],
    

In [17]:
np.random.rand(9)#9 elementos
np.random.rand(3,2)# 6 elementos 3x2 dimencion

array([[0.65909778, 0.08061157],
       [0.11061098, 0.43794111],
       [0.74170473, 0.98578651]])

In [18]:
np.average(arreglo_random)

14.125

In [19]:
np.mean(arreglo_random)

14.125

In [20]:
np.median(arreglo_random)

13.5

In [21]:
np.std(arreglo_random)

2.4206145913796355

In [22]:
np.var(arreglo_random)

5.859375

In [23]:
arreglo_random.mean()

14.125