In [1]:
import pandas as pd
import numpy as np

In [10]:
# 1) Crea un Dataframe de 10 registros y 6 columnas y consigue las 5 primeros y los 5 ultimos registros
df1 = pd.DataFrame(np.random.randint(0, 10, 60).reshape(10,6))

print("DataFrame\n",df1)
print("cinco primeros\n",df1.head())
print("cinco ultimos\n",df1.tail())

DataFrame
    0  1  2  3  4  5
0  4  0  9  7  6  6
1  2  8  5  0  6  9
2  5  0  2  1  8  2
3  3  2  8  2  8  5
4  0  0  8  4  7  9
5  7  7  2  7  0  0
6  4  9  4  8  7  6
7  8  6  4  5  5  7
8  8  7  7  0  4  6
9  9  8  6  5  1  5
cinco primeros
    0  1  2  3  4  5
0  4  0  9  7  6  6
1  2  8  5  0  6  9
2  5  0  2  1  8  2
3  3  2  8  2  8  5
4  0  0  8  4  7  9
cinco ultimos
    0  1  2  3  4  5
5  7  7  2  7  0  0
6  4  9  4  8  7  6
7  8  6  4  5  5  7
8  8  7  7  0  4  6
9  9  8  6  5  1  5


In [15]:
## 2) Crear un dataframe pasando un arreglo de numpy de 6 x 4 con una fecha como indice y con columnas A, B, C, D randomico

#                  A         B         C         D
# 2013-01-01  0.469112 -0.282863 -1.509059 -1.135632
# 2013-01-02  1.212112 -0.173215  0.119209 -1.044236
# 2013-01-03 -0.861849 -2.104569 -0.494929  1.071804
# 2013-01-04  0.721555 -0.706771 -1.039575  0.271860
# 2013-01-05 -0.424972  0.567020  0.276232 -1.087401
# 2013-01-06 -0.673690  0.113648 -1.478427  0.524988
from datetime import date
arreglo = np.random.randint(0,10,24).reshape(6, 4)
columnas = ['A', 'B', 'C', 'D']
indices = [date.today(),
           date.today(),
           date.today(),
           date.today(),
           date.today(),
           date.today()
        ]
df2 = pd.DataFrame(
        arreglo,
        columns = columnas,
        index = indices
        )
print("Indices\n",indices)
print("Dataframe\n",df2)

Indices
 [datetime.date(2020, 9, 22), datetime.date(2020, 9, 22), datetime.date(2020, 9, 22), datetime.date(2020, 9, 22), datetime.date(2020, 9, 22), datetime.date(2020, 9, 22)]
Dataframe
             A  B  C  D
2020-09-22  9  3  9  3
2020-09-22  3  5  1  1
2020-09-22  0  5  8  5
2020-09-22  5  0  3  8
2020-09-22  7  9  6  5
2020-09-22  2  5  1  7


In [21]:
## 4) Crear un Dataframe con 10 registros y 6 columnas y con una propiedad del Dataframe mostrar las columnas, con otro comando mostrar los valores.

df3 = pd.DataFrame(np.random.randint(0,10,60).reshape(10, 6))

print("Dataframe\n",df3)
print("columnas\n",df3.columns.values)
print("valores\n",df3.values)

Dataframe
    0  1  2  3  4  5
0  1  5  4  1  1  1
1  4  4  9  3  8  7
2  3  7  9  5  0  7
3  4  8  4  4  5  6
4  2  8  9  8  7  7
5  7  5  1  1  4  4
6  8  7  8  5  1  9
7  2  0  9  7  8  4
8  2  0  7  9  4  0
9  3  5  1  6  7  0
columnas
 [0 1 2 3 4 5]
valores
 [[1 5 4 1 1 1]
 [4 4 9 3 8 7]
 [3 7 9 5 0 7]
 [4 8 4 4 5 6]
 [2 8 9 8 7 7]
 [7 5 1 1 4 4]
 [8 7 8 5 1 9]
 [2 0 9 7 8 4]
 [2 0 7 9 4 0]
 [3 5 1 6 7 0]]


In [25]:
## 5) Crear un Dataframe con 10 registros y 6 columnas y con una funcion del Dataframe describir estadisticamente el Dataframe

df4 = pd.DataFrame(np.random.randint(0,10,60).reshape(10, 6))

print("Dataframa\n",df4)
print("Descripcion\n",df4.describe())

Dataframa
    0  1  2  3  4  5
0  0  9  4  7  4  8
1  7  5  5  6  3  0
2  9  1  3  1  0  5
3  9  7  0  2  8  0
4  1  0  4  0  0  1
5  4  4  7  1  2  9
6  6  1  1  7  9  8
7  7  8  7  1  2  2
8  7  4  2  8  8  5
9  1  6  7  5  8  1
Descripcion
                0          1          2          3          4          5
count  10.000000  10.000000  10.000000  10.000000  10.000000  10.000000
mean    5.100000   4.500000   4.000000   3.800000   4.400000   3.900000
std     3.381321   3.100179   2.538591   3.084009   3.533962   3.541814
min     0.000000   0.000000   0.000000   0.000000   0.000000   0.000000
25%     1.750000   1.750000   2.250000   1.000000   2.000000   1.000000
50%     6.500000   4.500000   4.000000   3.500000   3.500000   3.500000
75%     7.000000   6.750000   6.500000   6.750000   8.000000   7.250000
max     9.000000   9.000000   7.000000   8.000000   9.000000   9.000000


In [30]:

## 6) Crear un Dataframe con 10 registros y 6 columnas y con una funcion del Dataframe transponer los datos

df5 = pd.DataFrame(np.random.randint(0,10,60).reshape(10, 6))

print("Dataframa\n",df5)
print("Transpuesta\n",df5.transpose())

Dataframa
    0  1  2  3  4  5
0  7  3  1  7  2  9
1  0  6  6  4  2  1
2  2  0  3  4  0  0
3  1  3  3  3  3  1
4  3  0  5  7  0  3
5  2  9  8  6  5  5
6  2  4  7  7  1  2
7  8  1  2  1  8  8
8  4  8  0  8  8  1
9  7  4  8  3  2  7
Transpuesta
    0  1  2  3  4  5  6  7  8  9
0  7  0  2  1  3  2  2  8  4  7
1  3  6  0  3  0  9  4  1  8  4
2  1  6  3  3  5  8  7  2  0  8
3  7  4  4  3  7  6  7  1  8  3
4  2  2  0  3  0  5  1  8  8  2
5  9  1  0  1  3  5  2  8  1  7


In [47]:
## 7) Crear un Dataframe con 10 registros y 6 columnas y Ordenar el dataframe 1 vez por cada columna, ascendente y descendente

df6 = pd.DataFrame(np.random.randint(0,10,60).reshape(10, 6))

ascendente = df6.apply(lambda x: x.sort_values().values)
descendente = df6.apply(lambda x: x.sort_values(ascending = False).values)

print("Dataframa\n",df6)
print("Ascendente\n",ascendente)
print("Descendente\n",descendente)

Dataframa
    0  1  2  3  4  5
0  6  0  7  7  3  8
1  3  8  1  7  8  2
2  5  4  5  0  5  2
3  2  8  6  5  0  2
4  6  8  7  7  0  9
5  2  0  3  5  8  8
6  5  9  2  4  6  2
7  5  2  3  2  2  1
8  1  3  7  5  4  9
9  7  2  1  8  9  5
Ascendente
    0  1  2  3  4  5
0  1  0  1  0  0  1
1  2  0  1  2  0  2
2  2  2  2  4  2  2
3  3  2  3  5  3  2
4  5  3  3  5  4  2
5  5  4  5  5  5  5
6  5  8  6  7  6  8
7  6  8  7  7  8  8
8  6  8  7  7  8  9
9  7  9  7  8  9  9
Descendente
    0  1  2  3  4  5
0  7  9  7  8  9  9
1  6  8  7  7  8  9
2  6  8  7  7  8  8
3  5  8  6  7  6  8
4  5  4  5  5  5  5
5  5  3  3  5  4  2
6  3  2  3  5  3  2
7  2  2  2  4  2  2
8  2  0  1  2  0  2
9  1  0  1  0  0  1


In [53]:

## 8) Crear un Dataframe con 10 registros y 6 columnas llenas de números randomicos del 1 al 10 y seleccionar en un nuevo Dataframe solo los valores mayores a 7

df7 = pd.DataFrame(np.random.randint(1, 11,60).reshape(10,6), columns=list('ABCDEF'))

print("Dataframa\n",df7)
print("Mayores a 7\n",df7.where(df7>7))

Dataframa
    A   B   C   D  E   F
0  3   1   7   4  1   3
1  3   5   2   4  2   2
2  7  10  10  10  3   5
3  3   3   6   6  2  10
4  9   1  10   2  7   1
5  9   6   2   3  2  10
6  3   1   3   9  5   2
7  6   8  10   3  8   4
8  4   6   5   9  4   8
9  9   5  10   2  5  10
Mayores a 7
      A     B     C     D    E     F
0  NaN   NaN   NaN   NaN  NaN   NaN
1  NaN   NaN   NaN   NaN  NaN   NaN
2  NaN  10.0  10.0  10.0  NaN   NaN
3  NaN   NaN   NaN   NaN  NaN  10.0
4  9.0   NaN  10.0   NaN  NaN   NaN
5  9.0   NaN   NaN   NaN  NaN  10.0
6  NaN   NaN   NaN   9.0  NaN   NaN
7  NaN   8.0  10.0   NaN  8.0   NaN
8  NaN   NaN   NaN   9.0  NaN   8.0
9  9.0   NaN  10.0   NaN  NaN  10.0


In [66]:
## 9) Crear un Dataframe con 10 registros y 6 columnas llenas de números randomicos del 1 al 10 o valores NaN. Luego llenar los valores NaN con 0.

df8 = pd.DataFrame(np.random.randint(1,11,60).reshape(10, 6))
df8_nan = df8.where(df8>4)

print("Dataframa\n",df8)
print("Valores no NaN\n",df8_nan.fillna(0))

Dataframa
     0   1   2  3  4   5
0   9   1   7  8  4   6
1  10   8  10  4  9   6
2   3   6   9  9  7   1
3   4   4   5  7  4  10
4   5   1   9  6  6  10
5   7   6   3  4  9   5
6   6   7   1  8  4   5
7   2   4   5  2  6   8
8   2  10  10  4  2   2
9  10   8  10  2  5   2
Valores no NaN
       0     1     2    3    4     5
0   9.0   0.0   7.0  8.0  0.0   6.0
1  10.0   8.0  10.0  0.0  9.0   6.0
2   0.0   6.0   9.0  9.0  7.0   0.0
3   0.0   0.0   5.0  7.0  0.0  10.0
4   5.0   0.0   9.0  6.0  6.0  10.0
5   7.0   6.0   0.0  0.0  9.0   5.0
6   6.0   7.0   0.0  8.0  0.0   5.0
7   0.0   0.0   5.0  0.0  6.0   8.0
8   0.0  10.0  10.0  0.0  0.0   0.0
9  10.0   8.0  10.0  0.0  5.0   0.0


In [67]:
## 10) Crear un Dataframe con 10 registros y 6 columnas llenas de números randomicos del 1 al 10 y sacar la media, la mediana, el promedio

df9 = pd.DataFrame(np.random.randint(1,11,60).reshape(10, 6))

print("Dataframa\n",df9)
print("media\n",df9.mean())
print("mediana\n",df9.median())
print("promedio\n",np.average(df9))

Dataframa
     0  1   2   3   4   5
0  10  9   8   1   2   3
1  10  9   4   1   6   4
2   5  2   9   6  10   3
3   1  3  10   5  10  10
4   9  3   3   3  10  10
5   1  8  10   9  10   8
6   3  8   8   9   6   8
7   2  8   4   8   1   1
8  10  9  10  10  10   5
9   3  7   7   4   9  10
media
 0    5.4
1    6.6
2    7.3
3    5.6
4    7.4
5    6.2
dtype: float64
mediana
 0    4.0
1    8.0
2    8.0
3    5.5
4    9.5
5    6.5
dtype: float64
promedio
 6.416666666666667


In [73]:
## 11) Crear un Dataframe con 10 registros y 6 columnas llenas de números randomicos del 1 al 10, luego crear otro dateframe con 10 registros y 6 columnas llenas de números randomicos del 1 al 10 y anadirlo al primer Dataframe
df10 = pd.DataFrame(np.random.randint(1,11,60).reshape(10, 6))
df11 = pd.DataFrame(np.random.randint(1,11,60).reshape(10, 6))

print("Dataframa 1\n",df10)
print("Dataframa 2\n",df11)
print("Dataframa juntos\n",df10.append(df11))

Dataframa 1
     0   1   2  3   4   5
0   4   2   3  5  10   6
1  10   7   3  4   1   7
2   7   1   5  9  10   9
3   5   1   6  7   4   7
4  10  10  10  2   6   1
5   3   2   5  7   8   7
6   3  10   4  1  10   7
7   2  10  10  1   8   8
8   2   7   7  8   8   1
9   1   9   3  1  10  10
Dataframa 2
    0  1   2   3  4   5
0  5  1   7   8  1   8
1  7  7   4   5  6   7
2  1  1  10   6  3   1
3  4  4   7   7  4  10
4  4  8   2  10  9   8
5  4  3   1  10  4   5
6  4  8   3   7  8   6
7  8  7   3   9  3   3
8  4  6   8   9  4   7
9  8  6   6   6  8   3
Dataframa juntos
     0   1   2   3   4   5
0   4   2   3   5  10   6
1  10   7   3   4   1   7
2   7   1   5   9  10   9
3   5   1   6   7   4   7
4  10  10  10   2   6   1
5   3   2   5   7   8   7
6   3  10   4   1  10   7
7   2  10  10   1   8   8
8   2   7   7   8   8   1
9   1   9   3   1  10  10
0   5   1   7   8   1   8
1   7   7   4   5   6   7
2   1   1  10   6   3   1
3   4   4   7   7   4  10
4   4   8   2  10   9   8
5   4   3   

In [100]:
## 12) Crear un Dataframe con 10 registros y 6 columnas llenas de strings. Luego, unir la columna 1 y 2 en una sola, la 3 y 4, y la 5 y 6 concatenando su texto.

df12 = pd.DataFrame(np.random.choice(['uno', 'dos', 'tres', 'cuatro', 'cinco', 'seis'], 60).reshape(10,6))

df_final = pd.DataFrame(df12[0]+" "+df12[1])
df_final[1] = pd.DataFrame(df12[2]+" "+df12[3])
df_final[2] = pd.DataFrame(df12[4]+" "+df12[5])

print("Dataframa\n",df12)
print("Dataframa Final\n",df_final)

Dataframa
        0      1       2       3       4       5
0    uno    uno     uno    tres    tres     uno
1   tres    dos     dos    tres   cinco   cinco
2   tres   tres     uno     dos     uno  cuatro
3    uno    dos    seis   cinco     dos    tres
4  cinco    uno     uno    tres     uno    tres
5    uno    dos  cuatro     dos     dos     dos
6    dos  cinco    seis    seis  cuatro     dos
7   seis  cinco    tres   cinco   cinco    tres
8    uno    dos     dos  cuatro     dos  cuatro
9    uno  cinco    seis  cuatro    tres  cuatro
Dataframa Final
             0            1            2
0     uno uno     uno tres     tres uno
1    tres dos     dos tres  cinco cinco
2   tres tres      uno dos   uno cuatro
3     uno dos   seis cinco     dos tres
4   cinco uno     uno tres     uno tres
5     uno dos   cuatro dos      dos dos
6   dos cinco    seis seis   cuatro dos
7  seis cinco   tres cinco   cinco tres
8     uno dos   dos cuatro   dos cuatro
9   uno cinco  seis cuatro  tres cuatro


In [96]:
## 13) Crear un Dataframe con 10 registros y 6 columnas llenas de números randomicos del 1 al 10 enteros, obtener la frecuencia de repeticion de los numeros enteros en cada columna

df12 = pd.DataFrame(np.random.randint(1,11,60).reshape(10, 6))
print("Dataframa\n",df12)

for column in df12.columns.values:
    print("Columna " + str(column))
    print(df12[column].value_counts())
    

Dataframa
     0  1   2   3   4  5
0   8  9   9   9   4  3
1   3  1   7   1   6  8
2   1  7   3  10  10  4
3  10  3  10  10   2  6
4   5  9   4   2   3  2
5   8  4   7   9   6  6
6   3  6   7  10  10  6
7   4  8   8   7   3  2
8   9  1   7   4   5  8
9   7  7   9   7   2  3
Columna 0
8     2
3     2
10    1
9     1
7     1
5     1
4     1
1     1
Name: 0, dtype: int64
Columna 1
9    2
7    2
1    2
8    1
6    1
4    1
3    1
Name: 1, dtype: int64
Columna 2
7     4
9     2
10    1
8     1
4     1
3     1
Name: 2, dtype: int64
Columna 3
10    3
9     2
7     2
4     1
2     1
1     1
Name: 3, dtype: int64
Columna 4
10    2
6     2
3     2
2     2
5     1
4     1
Name: 4, dtype: int64
Columna 5
6    3
8    2
3    2
2    2
4    1
Name: 5, dtype: int64


In [92]:

## 14) Crear un Dataframe con 10 registros y 3 columnas, A B C, llenas de números randomicos del 1 al 10 enteros. Crear una nueva columna con el calculo por fila (A * B ) / C

df13 = pd.DataFrame(np.random.randint(1,10,30).reshape(10, 3), columns = ['A', 'B', 'C'])

print("Dataframa\n",df13)
df13['Calculo'] = ((df13['A'] * df13['B']) / df13['C'])
print("resultados\n",df13)

Dataframa
    A  B  C
0  1  5  5
1  5  4  8
2  3  9  4
3  3  9  9
4  5  3  4
5  5  6  9
6  2  5  1
7  3  1  9
8  8  1  3
9  2  7  8
resultados
    A  B  C    Calculo
0  1  5  5   1.000000
1  5  4  8   2.500000
2  3  9  4   6.750000
3  3  9  9   3.000000
4  5  3  4   3.750000
5  5  6  9   3.333333
6  2  5  1  10.000000
7  3  1  9   0.333333
8  8  1  3   2.666667
9  2  7  8   1.750000
